//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.36366
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salma2010.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salma2010.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activate.
        /// </summary>
        internal static string btnActivateLabel {
            get {
                return ResourceManager.GetString("btnActivateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Details.
        /// </summary>
        internal static string btnAddDetailsLabel {
            get {
                return ResourceManager.GetString("btnAddDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add work item details.
        /// </summary>
        internal static string btnAddDetailsToolTip {
            get {
                return ResourceManager.GetString("btnAddDetailsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collapse.
        /// </summary>
        internal static string btnCollapseWorkItemLabel {
            get {
                return ResourceManager.GetString("btnCollapseWorkItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect from TFS.
        /// </summary>
        internal static string btnConnect_disconnectToolTip {
            get {
                return ResourceManager.GetString("btnConnect_disconnectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        internal static string btnConnectLabel {
            get {
                return ResourceManager.GetString("btnConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect to TFS.
        /// </summary>
        internal static string btnConnectToolTip {
            get {
                return ResourceManager.GetString("btnConnectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect.
        /// </summary>
        internal static string btnDisconnectLabel {
            get {
                return ResourceManager.GetString("btnDisconnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expand.
        /// </summary>
        internal static string btnExpandWorkItemLabel {
            get {
                return ResourceManager.GetString("btnExpandWorkItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export Item.
        /// </summary>
        internal static string btnExportItemLabel {
            get {
                return ResourceManager.GetString("btnExportItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export work item.
        /// </summary>
        internal static string btnExportItemToolTip {
            get {
                return ResourceManager.GetString("btnExportItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string btnHelp_mnuLabel {
            get {
                return ResourceManager.GetString("btnHelp_mnuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string btnHelpLabel {
            get {
                return ResourceManager.GetString("btnHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View help or activate SALMA.
        /// </summary>
        internal static string btnHelpToolTip {
            get {
                return ResourceManager.GetString("btnHelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import Items.
        /// </summary>
        internal static string btnImportItemsLabel {
            get {
                return ResourceManager.GetString("btnImportItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import work items.
        /// </summary>
        internal static string btnImportItemsToolTip {
            get {
                return ResourceManager.GetString("btnImportItemsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link Items.
        /// </summary>
        internal static string btnLinkItemsLabel {
            get {
                return ResourceManager.GetString("btnLinkItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link work items to internal or external resource.
        /// </summary>
        internal static string btnLinkItemsToolTip {
            get {
                return ResourceManager.GetString("btnLinkItemsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Traceability Matrix.
        /// </summary>
        internal static string btnMatrixLabel {
            get {
                return ResourceManager.GetString("btnMatrixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate traceability matrix containing TFS data.
        /// </summary>
        internal static string btnMatrixToolTip {
            get {
                return ResourceManager.GetString("btnMatrixToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create New.
        /// </summary>
        internal static string btnNewWorkItemLabel {
            get {
                return ResourceManager.GetString("btnNewWorkItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new work item.
        /// </summary>
        internal static string btnNewWorkItemToolTip {
            get {
                return ResourceManager.GetString("btnNewWorkItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Obsolete Work Item.
        /// </summary>
        internal static string btnObsoleteWorkItemLabel {
            get {
                return ResourceManager.GetString("btnObsoleteWorkItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Item.
        /// </summary>
        internal static string btnOpenWorkItemLabel {
            get {
                return ResourceManager.GetString("btnOpenWorkItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open work item.
        /// </summary>
        internal static string btnOpenWorkItemToolTip {
            get {
                return ResourceManager.GetString("btnOpenWorkItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate Report.
        /// </summary>
        internal static string btnReportLabel {
            get {
                return ResourceManager.GetString("btnReportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate TFS report based on existing queries.
        /// </summary>
        internal static string btnReportToolTip {
            get {
                return ResourceManager.GetString("btnReportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Panel.
        /// </summary>
        internal static string btnShowPanelLabel {
            get {
                return ResourceManager.GetString("btnShowPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Comments.
        /// </summary>
        internal static string btnShowWorkItemsLabel {
            get {
                return ResourceManager.GetString("btnShowWorkItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show/hide comments with TFS data.
        /// </summary>
        internal static string btnShowWorkItemsToolTip {
            get {
                return ResourceManager.GetString("btnShowWorkItemsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch TFS Account.
        /// </summary>
        internal static string btnSwitchTfsUserLabel {
            get {
                return ResourceManager.GetString("btnSwitchTfsUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch TFS user.
        /// </summary>
        internal static string btnSwitchTfsUserToolTip {
            get {
                return ResourceManager.GetString("btnSwitchTfsUserToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update Items.
        /// </summary>
        internal static string btnUpdateAndSyncLabel {
            get {
                return ResourceManager.GetString("btnUpdateAndSyncLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refreshing work item status and content at document.
        /// </summary>
        internal static string btnUpdateAndSyncToolTip {
            get {
                return ResourceManager.GetString("btnUpdateAndSyncToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import content.
        /// </summary>
        internal static string btnUpdateLabel {
            get {
                return ResourceManager.GetString("btnUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refreshing work item status at document.
        /// </summary>
        internal static string btnUpdateToolTip {
            get {
                return ResourceManager.GetString("btnUpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter connection URL.
        /// </summary>
        internal static string connectionBoxToolTip {
            get {
                return ResourceManager.GetString("connectionBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Area Path.
        /// </summary>
        internal static string ddlAreasLabel {
            get {
                return ResourceManager.GetString("ddlAreasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link Type.
        /// </summary>
        internal static string ddlLinksLabel {
            get {
                return ResourceManager.GetString("ddlLinksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TPC List.
        /// </summary>
        internal static string ddlProjectCollectionLabel {
            get {
                return ResourceManager.GetString("ddlProjectCollectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select team project collection.
        /// </summary>
        internal static string ddlProjectCollectionToolTip {
            get {
                return ResourceManager.GetString("ddlProjectCollectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Projects.
        /// </summary>
        internal static string ddlProjectsLabel {
            get {
                return ResourceManager.GetString("ddlProjectsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select team project.
        /// </summary>
        internal static string ddlProjectsToolTip {
            get {
                return ResourceManager.GetString("ddlProjectsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        internal static string edbLinkWiIDLabel {
            get {
                return ResourceManager.GetString("edbLinkWiIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Item.
        /// </summary>
        internal static string edbLinkWiLabel {
            get {
                return ResourceManager.GetString("edbLinkWiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reporting.
        /// </summary>
        internal static string group1Label {
            get {
                return ResourceManager.GetString("group1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Projects.
        /// </summary>
        internal static string group2Label {
            get {
                return ResourceManager.GetString("group2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Items.
        /// </summary>
        internal static string group3Label {
            get {
                return ResourceManager.GetString("group3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect to TFS.
        /// </summary>
        internal static string groupConnectLabel {
            get {
                return ResourceManager.GetString("groupConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default Link.
        /// </summary>
        internal static string groupDefaultsLabel {
            get {
                return ResourceManager.GetString("groupDefaultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string groupHelpLabel {
            get {
                return ResourceManager.GetString("groupHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Items.
        /// </summary>
        internal static string groupManageWILabel {
            get {
                return ResourceManager.GetString("groupManageWILabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reporting.
        /// </summary>
        internal static string groupReportingLabel {
            get {
                return ResourceManager.GetString("groupReportingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SALMA – Accept All Changes required.
        /// </summary>
        internal static string lblAcceptAllChangesRequiredCaptionLabel {
            get {
                return ResourceManager.GetString("lblAcceptAllChangesRequiredCaptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SALMA is going to accept all tracking changes in this document. Do you wish to proceed?.
        /// </summary>
        internal static string lblAcceptAllChangesRequiredLabel {
            get {
                return ResourceManager.GetString("lblAcceptAllChangesRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error to add data.
        /// </summary>
        internal static string lblAddReplaceWorkItemErrorLabel {
            get {
                return ResourceManager.GetString("lblAddReplaceWorkItemErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work item cannot be updated in the control {0}.
        /// </summary>
        internal static string lblApplyWorkItemErrorLabel {
            get {
                return ResourceManager.GetString("lblApplyWorkItemErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection URL.
        /// </summary>
        internal static string lblConnectionUrlLabel {
            get {
                return ResourceManager.GetString("lblConnectionUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Control is not connected with work item.
        /// </summary>
        internal static string lblOpenWorkItemErrorLabel {
            get {
                return ResourceManager.GetString("lblOpenWorkItemErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work items.
        /// </summary>
        internal static string lblTaskPaneLabel {
            get {
                return ResourceManager.GetString("lblTaskPaneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not logged in.
        /// </summary>
        internal static string lblTextNotLoggedIn {
            get {
                return ResourceManager.GetString("lblTextNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not logged in.
        /// </summary>
        internal static string menuTfsUserLabel {
            get {
                return ResourceManager.GetString("menuTfsUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display current TFS user.
        /// </summary>
        internal static string menuTfsUserToolTip {
            get {
                return ResourceManager.GetString("menuTfsUserToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide.
        /// </summary>
        internal static string showWorkItems_hideLabel {
            get {
                return ResourceManager.GetString("showWorkItems_hideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Comments.
        /// </summary>
        internal static string showWorkItemsLabel {
            get {
                return ResourceManager.GetString("showWorkItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected.
        /// </summary>
        internal static string splitBtnConnect_connectedLabel {
            get {
                return ResourceManager.GetString("splitBtnConnect_connectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        internal static string splitBtnConnectLabel {
            get {
                return ResourceManager.GetString("splitBtnConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logged in as: .
        /// </summary>
        internal static string statusLabel_loggedInLabel {
            get {
                return ResourceManager.GetString("statusLabel_loggedInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add work item details.
        /// </summary>
        internal static string TIP_ADD_WORK_ITEM_DETAILS {
            get {
                return ResourceManager.GetString("TIP_ADD_WORK_ITEM_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect to TFS.
        /// </summary>
        internal static string TIP_CONNECT_TO_TFS {
            get {
                return ResourceManager.GetString("TIP_CONNECT_TO_TFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new work item.
        /// </summary>
        internal static string TIP_CREATE_NEW_WORK_ITEM {
            get {
                return ResourceManager.GetString("TIP_CREATE_NEW_WORK_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect from TFS.
        /// </summary>
        internal static string TIP_DISCONNECT_FROM_TFS {
            get {
                return ResourceManager.GetString("TIP_DISCONNECT_FROM_TFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter connection URL.
        /// </summary>
        internal static string TIP_ENTER_CONNECTION_URL {
            get {
                return ResourceManager.GetString("TIP_ENTER_CONNECTION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate traceability matrix containing TFS data.
        /// </summary>
        internal static string TIP_GENERATE_MATRIX_BUTTON {
            get {
                return ResourceManager.GetString("TIP_GENERATE_MATRIX_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate TFS report based on existing queries.
        /// </summary>
        internal static string TIP_GENERATE_REPORT_BUTTON {
            get {
                return ResourceManager.GetString("TIP_GENERATE_REPORT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View help or activate SALMA.
        /// </summary>
        internal static string TIP_HELP_BUTTON {
            get {
                return ResourceManager.GetString("TIP_HELP_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link work items to internal or external resources.
        /// </summary>
        internal static string TIP_LINK_WORK_ITEMS {
            get {
                return ResourceManager.GetString("TIP_LINK_WORK_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select team project.
        /// </summary>
        internal static string TIP_SELECT_TEAM_PROJECT {
            get {
                return ResourceManager.GetString("TIP_SELECT_TEAM_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select team project collection.
        /// </summary>
        internal static string TIP_SELECT_TEAM_PROJECT_COLLECTION {
            get {
                return ResourceManager.GetString("TIP_SELECT_TEAM_PROJECT_COLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show/hide comments with TFS data.
        /// </summary>
        internal static string TIP_SHOW_HIDE_COMMENTS {
            get {
                return ResourceManager.GetString("TIP_SHOW_HIDE_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update work item information from TFS.
        /// </summary>
        internal static string TIP_UPDATE_BUTTON {
            get {
                return ResourceManager.GetString("TIP_UPDATE_BUTTON", resourceCulture);
            }
        }
    }
}
