//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.36366
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordToTFS.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordToTFS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string AddDetails_Add_Label {
            get {
                return ResourceManager.GetString("AddDetails_Add_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Details as.
        /// </summary>
        public static string AddDetails_As_Label {
            get {
                return ResourceManager.GetString("AddDetails_As_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Work Item ID.
        /// </summary>
        public static string AddDetails_By_Work_Item_ID_Tab {
            get {
                return ResourceManager.GetString("AddDetails_By_Work_Item_ID_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string AddDetails_Cancel_Label {
            get {
                return ResourceManager.GetString("AddDetails_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Work Item.
        /// </summary>
        public static string AddDetails_Choose_Work_Item_Label {
            get {
                return ResourceManager.GetString("AddDetails_Choose_Work_Item_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Document.
        /// </summary>
        public static string AddDetails_Current_Document_Tab {
            get {
                return ResourceManager.GetString("AddDetails_Current_Document_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter Work Items by Type.
        /// </summary>
        public static string AddDetails_Filter_Work_Items_By_Type_Label {
            get {
                return ResourceManager.GetString("AddDetails_Filter_Work_Items_By_Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace.
        /// </summary>
        public static string AddDetails_Replace_Label {
            get {
                return ResourceManager.GetString("AddDetails_Replace_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add details to work item.
        /// </summary>
        public static string AddDetails_Title {
            get {
                return ResourceManager.GetString("AddDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Item ID.
        /// </summary>
        public static string AddDetails_Work_Item_ID {
            get {
                return ResourceManager.GetString("AddDetails_Work_Item_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Connect_Cancel_Label {
            get {
                return ResourceManager.GetString("Connect_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Connect_Login_Label {
            get {
                return ResourceManager.GetString("Connect_Login_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Connect_Password_Label {
            get {
                return ResourceManager.GetString("Connect_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        public static string Connect_Title {
            get {
                return ResourceManager.GetString("Connect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Name.
        /// </summary>
        public static string Connect_User_Name_Label {
            get {
                return ResourceManager.GetString("Connect_User_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CreateNew_Cancel_Label {
            get {
                return ResourceManager.GetString("CreateNew_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string CreateNew_Create_Label {
            get {
                return ResourceManager.GetString("CreateNew_Create_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new work item.
        /// </summary>
        public static string CreateNew_Title {
            get {
                return ResourceManager.GetString("CreateNew_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string CreateNew_Title_Label {
            get {
                return ResourceManager.GetString("CreateNew_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Item Type.
        /// </summary>
        public static string CreateNew_Work_Item_Type_Label {
            get {
                return ResourceManager.GetString("CreateNew_Work_Item_Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a date.
        /// </summary>
        public static string DatePickerWatermark {
            get {
                return ResourceManager.GetString("DatePickerWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to create work item. Item contain required &apos;{0}&apos; field that have to be filled..
        /// </summary>
        public static string ERROR_MESSAGE_UNABLE_TO_CREATE_ITEM_WITH_REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE_UNABLE_TO_CREATE_ITEM_WITH_REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string ErrorDialog_Ok_Button {
            get {
                return ResourceManager.GetString("ErrorDialog_Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        public static string ErrorDialog_Title {
            get {
                return ResourceManager.GetString("ErrorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string ExportDialog_Cancel_Button {
            get {
                return ResourceManager.GetString("ExportDialog_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SALMA is going to accept all tracking changes in this document. Do you wish to proceed?.
        /// </summary>
        public static string ExportDialog_Message {
            get {
                return ResourceManager.GetString("ExportDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string ExportDialog_Ok_Button {
            get {
                return ResourceManager.GetString("ExportDialog_Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SALMA – Accept All Changes.
        /// </summary>
        public static string ExportDialog_Title {
            get {
                return ResourceManager.GetString("ExportDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string ImportDialog_Cancel_Button {
            get {
                return ResourceManager.GetString("ImportDialog_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import.
        /// </summary>
        public static string ImportDialog_Import_Button {
            get {
                return ResourceManager.GetString("ImportDialog_Import_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import work items.
        /// </summary>
        public static string ImportDialog_Title {
            get {
                return ResourceManager.GetString("ImportDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create control for empty description.
        /// </summary>
        public static string ImporteDialog_CheckBox {
            get {
                return ResourceManager.GetString("ImporteDialog_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format corrupted.
        /// </summary>
        public static string lblFormatCorruptedLabel {
            get {
                return ResourceManager.GetString("lblFormatCorruptedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string LinkItem_Cancel_Label {
            get {
                return ResourceManager.GetString("LinkItem_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Work Item.
        /// </summary>
        public static string LinkItem_Choose_Work_Item {
            get {
                return ResourceManager.GetString("LinkItem_Choose_Work_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments.
        /// </summary>
        public static string LinkItem_Comments {
            get {
                return ResourceManager.GetString("LinkItem_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Document.
        /// </summary>
        public static string LinkItem_Existing_Document {
            get {
                return ResourceManager.GetString("LinkItem_Existing_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter Work Items by Type.
        /// </summary>
        public static string LinkItem_Filter_Work_Items_By_Type_Label {
            get {
                return ResourceManager.GetString("LinkItem_Filter_Work_Items_By_Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hyperlink.
        /// </summary>
        public static string LinkItem_HyperLink {
            get {
                return ResourceManager.GetString("LinkItem_HyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hyperlink.
        /// </summary>
        public static string LinkItem_Hyperlink_LABEL {
            get {
                return ResourceManager.GetString("LinkItem_Hyperlink_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link Item as.
        /// </summary>
        public static string LinkItem_Link_Item_As {
            get {
                return ResourceManager.GetString("LinkItem_Link_Item_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link Item.
        /// </summary>
        public static string LinkItem_LinkItem_Label {
            get {
                return ResourceManager.GetString("LinkItem_LinkItem_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Outside Document.
        /// </summary>
        public static string LinkItem_Outside_Document {
            get {
                return ResourceManager.GetString("LinkItem_Outside_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link item to.
        /// </summary>
        public static string LinkItem_Title {
            get {
                return ResourceManager.GetString("LinkItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Item IDs.
        /// </summary>
        public static string LinkItem_Work_Item_IDs {
            get {
                return ResourceManager.GetString("LinkItem_Work_Item_IDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Item Type.
        /// </summary>
        public static string LinkItem_Work_Item_Type {
            get {
                return ResourceManager.GetString("LinkItem_Work_Item_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string MatrixReport_Cancel {
            get {
                return ResourceManager.GetString("MatrixReport_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Columns.
        /// </summary>
        public static string MatrixReport_Columns {
            get {
                return ResourceManager.GetString("MatrixReport_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created Date.
        /// </summary>
        public static string MatrixReport_Created_Date {
            get {
                return ResourceManager.GetString("MatrixReport_Created_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string MatrixReport_Date {
            get {
                return ResourceManager.GetString("MatrixReport_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date from.
        /// </summary>
        public static string MatrixReport_Date_From {
            get {
                return ResourceManager.GetString("MatrixReport_Date_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date to.
        /// </summary>
        public static string MatrixReport_Date_To {
            get {
                return ResourceManager.GetString("MatrixReport_Date_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From.
        /// </summary>
        public static string MatrixReport_From {
            get {
                return ResourceManager.GetString("MatrixReport_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Include not linked Items.
        /// </summary>
        public static string MatrixReport_Include_Not_Linked_Items {
            get {
                return ResourceManager.GetString("MatrixReport_Include_Not_Linked_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert.
        /// </summary>
        public static string MatrixReport_Insert {
            get {
                return ResourceManager.GetString("MatrixReport_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link Type.
        /// </summary>
        public static string MatrixReport_Link_Type {
            get {
                return ResourceManager.GetString("MatrixReport_Link_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rows.
        /// </summary>
        public static string MatrixReport_Rows {
            get {
                return ResourceManager.GetString("MatrixReport_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State.
        /// </summary>
        public static string MatrixReport_State {
            get {
                return ResourceManager.GetString("MatrixReport_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Matrix report.
        /// </summary>
        public static string MatrixReport_Title {
            get {
                return ResourceManager.GetString("MatrixReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To.
        /// </summary>
        public static string MatrixReport_To {
            get {
                return ResourceManager.GetString("MatrixReport_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The following required fields will be filled with default values:.
        /// </summary>
        public static string MESSAGE_ITEMS_WITH_DEFAULT_FIELDS {
            get {
                return ResourceManager.GetString("MESSAGE_ITEMS_WITH_DEFAULT_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string Obolete_List_Item_Copy {
            get {
                return ResourceManager.GetString("Obolete_List_Item_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move.
        /// </summary>
        public static string Obolete_List_Item_Move {
            get {
                return ResourceManager.GetString("Obolete_List_Item_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action.
        /// </summary>
        public static string Obsolete_List_Action_Title {
            get {
                return ResourceManager.GetString("Obsolete_List_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string Obsolete_List_WIId_Title {
            get {
                return ResourceManager.GetString("Obsolete_List_WIId_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link End.
        /// </summary>
        public static string Obsolete_List_WILink_Title {
            get {
                return ResourceManager.GetString("Obsolete_List_WILink_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string Obsolete_List_WITitle_Title {
            get {
                return ResourceManager.GetString("Obsolete_List_WITitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Item Type.
        /// </summary>
        public static string Obsolete_List_WIType_Title {
            get {
                return ResourceManager.GetString("Obsolete_List_WIType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string ObsoleteWorkItem_Cancel_Lablel {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Cancel_Lablel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Obsolete Work Item label.
        /// </summary>
        public static string ObsoleteWorkItem_Label_Item {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Label_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Links.
        /// </summary>
        public static string ObsoleteWorkItem_Label_Links {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Label_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string ObsoleteWorkItem_Ok_Label {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Ok_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add to Tags.
        /// </summary>
        public static string ObsoleteWorkItem_Tag_Item {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Tag_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duplicate Work Item.
        /// </summary>
        public static string ObsoleteWorkItem_Title {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add to Title.
        /// </summary>
        public static string ObsoleteWorkItem_Title_Item {
            get {
                return ResourceManager.GetString("ObsoleteWorkItem_Title_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string Progress_Stop {
            get {
                return ResourceManager.GetString("Progress_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body Text.
        /// </summary>
        public static string QueryReport_Body_Text {
            get {
                return ResourceManager.GetString("QueryReport_Body_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Queries.
        /// </summary>
        public static string QueryReport_By_Queries_Tab {
            get {
                return ResourceManager.GetString("QueryReport_By_Queries_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Work Item IDs.
        /// </summary>
        public static string QueryReport_By_WI_ID_Tab {
            get {
                return ResourceManager.GetString("QueryReport_By_WI_ID_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string QueryReport_Cancel {
            get {
                return ResourceManager.GetString("QueryReport_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Header.
        /// </summary>
        public static string QueryReport_Header {
            get {
                return ResourceManager.GetString("QueryReport_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Include Attachments.
        /// </summary>
        public static string QueryReport_Include_Attachments {
            get {
                return ResourceManager.GetString("QueryReport_Include_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert.
        /// </summary>
        public static string QueryReport_Insert {
            get {
                return ResourceManager.GetString("QueryReport_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of Queries.
        /// </summary>
        public static string QueryReport_List_Of_Queries {
            get {
                return ResourceManager.GetString("QueryReport_List_Of_Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage Queries.
        /// </summary>
        public static string QueryReport_Manage_Queries {
            get {
                return ResourceManager.GetString("QueryReport_Manage_Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metadata.
        /// </summary>
        public static string QueryReport_Metadata {
            get {
                return ResourceManager.GetString("QueryReport_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can type multiple WI, separated by commas..
        /// </summary>
        public static string QueryReport_Multiple_WI {
            get {
                return ResourceManager.GetString("QueryReport_Multiple_WI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Work items that don&apos;t belong to the current project will not be included to the report..
        /// </summary>
        public static string QueryReport_Not_In_Current_Document_Message {
            get {
                return ResourceManager.GetString("QueryReport_Not_In_Current_Document_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report Format.
        /// </summary>
        public static string QueryReport_Report_Format {
            get {
                return ResourceManager.GetString("QueryReport_Report_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Revision Date.
        /// </summary>
        public static string QueryReport_RevisionDate_Text {
            get {
                return ResourceManager.GetString("QueryReport_RevisionDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report.
        /// </summary>
        public static string QueryReport_Title {
            get {
                return ResourceManager.GetString("QueryReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Items IDs.
        /// </summary>
        public static string QueryReport_Work_Items_ID {
            get {
                return ResourceManager.GetString("QueryReport_Work_Items_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fields.
        /// </summary>
        public static string RequiredFields_Fields_plural {
            get {
                return ResourceManager.GetString("RequiredFields_Fields_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field.
        /// </summary>
        public static string RequiredFields_Fields_singular {
            get {
                return ResourceManager.GetString("RequiredFields_Fields_singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на must contain numeric value.
        /// </summary>
        public static string RequiredFields_Must_Contain_Numeric_Value_plural {
            get {
                return ResourceManager.GetString("RequiredFields_Must_Contain_Numeric_Value_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на must contain numeric value.
        /// </summary>
        public static string RequiredFields_Must_Contain_Numeric_Value_singular {
            get {
                return ResourceManager.GetString("RequiredFields_Must_Contain_Numeric_Value_singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на are required.
        /// </summary>
        public static string RequiredFields_Required_plural {
            get {
                return ResourceManager.GetString("RequiredFields_Required_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is required.
        /// </summary>
        public static string RequiredFields_Required_singular {
            get {
                return ResourceManager.GetString("RequiredFields_Required_singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на See attachments.
        /// </summary>
        public static string SeeAttachments_Text {
            get {
                return ResourceManager.GetString("SeeAttachments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action.
        /// </summary>
        public static string StepActionsResult_Action_Label {
            get {
                return ResourceManager.GetString("StepActionsResult_Action_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string StepActionsResult_Add_Button {
            get {
                return ResourceManager.GetString("StepActionsResult_Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string StepActionsResult_Cancel_Button {
            get {
                return ResourceManager.GetString("StepActionsResult_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expected Result.
        /// </summary>
        public static string StepActionsResult_Expected_Result_Label {
            get {
                return ResourceManager.GetString("StepActionsResult_Expected_Result_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding Step.
        /// </summary>
        public static string StepActionsResult_Title {
            get {
                return ResourceManager.GetString("StepActionsResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string UpdateDialog_Cancel_Button {
            get {
                return ResourceManager.GetString("UpdateDialog_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import content.
        /// </summary>
        public static string UpdateDialog_CheckBox {
            get {
                return ResourceManager.GetString("UpdateDialog_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SALMA is going to accept all tracking changes in this document. Do you wish to proceed?.
        /// </summary>
        public static string UpdateDialog_Message {
            get {
                return ResourceManager.GetString("UpdateDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string UpdateDialog_Ok_Button {
            get {
                return ResourceManager.GetString("UpdateDialog_Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SALMA – Accept All Changes.
        /// </summary>
        public static string UpdateDialog_Title {
            get {
                return ResourceManager.GetString("UpdateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WordSectionGroup/Word2007Section.
        /// </summary>
        public static string Word2007Section {
            get {
                return ResourceManager.GetString("Word2007Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WordSectionGroup/WordSection.
        /// </summary>
        public static string WordSection {
            get {
                return ResourceManager.GetString("WordSection", resourceCulture);
            }
        }
    }
}
